"use client"
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { store } from '../redux/store/store'
import { Provider } from 'react-redux'
import { useState, useEffect } from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setTheme] = useState(localStorage.getItem("theme") || "white");
  useEffect(() => {
    const storedTheme = localStorage.getItem("theme");
    if (storedTheme) {
      setTheme(storedTheme);
    }
  }, []);
  return (
    <html lang="en" >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${theme === "white" ? "bg-white": "bg-dark border-gray-600"}`}
      >
         <Provider store={store}>
          
        {children}
         </Provider>
      </body>
    </html>
  );
}
